- name: Update APT package list (for Ubuntu)
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install OpenJDK 11 (for Ubuntu)
  apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Verify Java installation
  command: java -version
  register: java_version_output
  ignore_errors: yes

- name: Display Java version
  debug:
    msg: "{{ java_version_output.stdout }}"
  when: java_version_output is defined
