- name: Ensure Python3 is installed
  ansible.builtin.apt:
    name: python3
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Ensure pip3 is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install boto3, botocore, and packaging using pip3
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
      - packaging
    executable: pip3
