- name: Set hostname based on Name tag
  ansible.builtin.hostname:
    name: "{{ tags.Name }}"
  when: tags.Name is defined

- name: Ensure hostname is persisted in /etc/hostname
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ tags.Name }}"
  when: tags.Name is defined

- name: Ensure /etc/hosts is updated
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ tags.Name }}"
    state: present
    insertafter: '^127\.0\.0\.1 localhost'
  when: tags.Name is defined
