- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update apt cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Ensure Docker is enabled and started
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add ubuntu user to Docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  when: ansible_distribution == "Ubuntu" and ansible_user == "ubuntu"

# Verify Docker installation
- name: Check Docker version
  ansible.builtin.command: docker --version
  register: docker_version_output
  changed_when: docker_version_output.rc != 0

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version_output.stdout
