---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    #changed_when: false
    when: ansible_distribution == "Ubuntu"


- name: Install Docker Engine on the private instances
  hosts: backend
  become: true
  roles:
    - docker
