---
- name: Install Docker Engine on the private instances
  hosts: private_instances
  become: true
  tasks:

    # Update apt package index
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install prerequisites
    - name: Install prerequisite packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker’s official GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Set up Docker stable repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Update apt cache after adding Docker repository
    - name: Update apt cache after Docker repo
      apt:
        update_cache: yes

    # Install Docker Engine
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    # Ensure Docker service is enabled and started
    - name: Ensure Docker is running
      systemd:
        name: docker
        enabled: yes
        state: started

    # Add current user to the Docker group (optional, for non-root usage)
    - name: Add ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      when: ansible_user == "ubuntu"

    # Verify Docker installation
    - name: Check Docker version
      command: docker --version
      register: docker_version_output

    - debug:
        var: docker_version_output.stdout
