---
- name: Update repository index
  hosts: aws_ec2
  become: true
  pre_tasks:
    - name: Update repository index (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- name: Install Docker Engine on the private instances
  hosts: aws_ec2
  become: true
  roles:
    - docker
