---
- name: Setup Terraform, AWS CLI, and Python on localhost
  hosts: localhost
  become: true
  pre_tasks:
    - name: Update repository index (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"
  roles:
    - boto3
    - terraform
    - aws_cli
